name: babbleapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  google_sign_in: ^5.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - asset/images/babblelogo.png
   - asset/images/babblelogotext.png
   - asset/images/facebooklogo.png
   - asset/images/googleLogo.png

